create table if not exists subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  status text not null default 'active' check (status in ('active', 'unsubscribed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists sources (
  id bigint generated by default as identity primary key,
  name text not null,
  url text unique not null,
  type text not null default 'rss' check (type in ('rss', 'api')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists news_items (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  canonical_url text not null,
  url_hash text unique not null,
  summary text,
  published_at timestamptz,
  source_name text,
  source_url text,
  raw_json jsonb,
  ingested_at timestamptz not null default now()
);

create table if not exists digests (
  id bigint generated by default as identity primary key,
  digest_date date not null,
  category text not null,
  status text not null default 'draft' check (status in ('draft', 'approved', 'sent', 'skipped')),
  content_json jsonb not null,
  generation_meta jsonb,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  sent_at timestamptz,
  unique (digest_date, category)
);

create table if not exists send_logs (
  id bigint generated by default as identity primary key,
  digest_id bigint references digests(id) on delete cascade,
  email text not null,
  status text not null,
  error text,
  created_at timestamptz not null default now()
);

create table if not exists settings (
  key text primary key,
  value_json jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_subscribers_status on subscribers(status);
create index if not exists idx_sources_is_active on sources(is_active);
create index if not exists idx_news_items_ingested_at on news_items(ingested_at desc);
create index if not exists idx_send_logs_digest_id on send_logs(digest_id);
